### ISSUE TITLE
failure to list bitbucket repos

### ISSUE THREAD

**Issue by jonhadfield** [jonhadfield/soba#4]
```
soba: 2018/07/16 13:54:22 main.go:113: [0.0.10-34938ba] 2018/07/14:18:26:39 UTC
soba: 2018/07/16 13:54:22 main.go:115: starting
soba: 2018/07/16 13:54:22 main.go:132: creating working directory:  /backup/.working
soba: 2018/07/16 13:54:22 main.go:161: backing up BitBucket repos
soba: 2018/07/16 13:54:22 bitbucket.go:31: listing BitBucket repositories
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x60743a]
goroutine 1 [running]:
github.com/jonhadfield/soba/githosts.bitbucketHost.describeRepos(0x69c57b, 0x9, 0x6a28da, 0x1d, 0xc420045900, 0xa1, 0xa10060ef82)
	/Users/hadfielj/Repositories/gocode/src/github.com/jonhadfield/soba/githosts/bitbucket.go:45 +0x22a
github.com/jonhadfield/soba/githosts.bitbucketHost.Backup(0x69c57b, 0x9, 0x6a28da, 0x1d, 0xc42001620f, 0x7)
	/Users/hadfielj/Repositories/gocode/src/github.com/jonhadfield/soba/githosts/bitbucket.go:73 +0x6a
github.com/jonhadfield/soba/githosts.Backup(0x69c66e, 0x9, 0xc42001620f, 0x7)
	/Users/hadfielj/Repositories/gocode/src/github.com/jonhadfield/soba/githosts/main.go:52 +0xd0
main.execProviderBackups()
	/Users/hadfielj/Repositories/gocode/src/github.com/jonhadfield/soba/main.go:162 +0x62f
main.main()
	/Users/hadfielj/Repositories/gocode/src/github.com/jonhadfield/soba/main.go:153 +0x52f 
```

**Comment by jonhadfield** [comment]
Cannot reproduce.
